### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by Foodstamp001** [ProjectAwesomeGaming/Community-Feedback#36] opened 2018-01-29 20:15 UTC
Names still aren't showing up when you hover over people, and UI elements are missing such as altitude when HALO dropping

**Comment by jonas232** [comment] 2018-01-30 08:14
Vanilla HALO or 3rd party scripted HALO? @Foodstamp001

**Comment by Hamster2k** [comment] 2018-01-30 10:20
First half of your issue is a duplicate of #30 and fixed (please keep issues seperate from now on).

What other UI elements are missing? Which mission did it happen on? Liberation deploys their own cba mission config that overrides a lot of our server config and I don't want to force override everything in our settings. Is the lacking altitude gauge a big deal?

**Comment by Foodstamp001** [comment] 2018-01-30 13:50
It's not mission specific. It's happening in D. recon and lib. Altitude and airspeed are very important when jumping...

**Comment by Hamster2k** [comment] 2018-01-30 15:01
https://github.com/acemod/ACE3/pull/5836

**Comment by Hamster2k** [comment] 2018-01-30 15:15
The setting to hide the altimeter is currently turned off, but can be overridden by client and mission. Please check your personal and/or the mission settings!

**Comment by Hamster2k** [comment] 2018-01-30 15:23
I just loaded up Sahrani Lib and I see both speed and altitude. Seems like you have it set to hidden in your personal settings :D

**Closed as completed by Hamster2k** 2018-01-30 15:23 UTC
