### ISSUE TITLE
swifty.projectawesome.net spelling error

### ISSUE THREAD

**Issue by ProjectAwesomeGaming** [ProjectAwesomeGaming/Community-Feedback#2] opened 2018-01-10 18:40 UTC
http://swifty.projectawesome.net/install.htm

Link doesn't know how to spell. The tab says, "Switfy for PA".

**Comment by linkspec** [comment] 2018-01-10 18:50
Duplicate of https://github.com/ProjectAwesomeGaming/main/issues/1

**Closed as completed by linkspec** 2018-01-10 18:50 UTC
